lenguage: java
branches:
  only:
    - develop
notifications:
  slack: nervespacio:VL5daOHOAjyMrg0Fm1oq7brj
  email:
    recipients:
      - vladimirogaston@gmail.com
script:
  - mvn verify
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install
  - mvn sonar:sonar -Dsonar.organization=vladimirogaston -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR